[build]
  command = "npm run build"
  publish = "dist"

# Поддержка React Router в подпапке
[[redirects]]
  from = "/react/*"
  to = "/react/index.html"
  status = 200

# Опционально: если у тебя JS-приложение тоже использует роутинг
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { Country = [] }